### ISSUE TITLE
Add cake-contrib user

### ISSUE THREAD

**Issue by gep13** [hadi77ir/Cake.Rest#3]
First of all, I wanted to thank you for adding to the Cake community by adding this addin.

I was just wondering if you had seen this blog post:

http://cakebuild.net/blog/2016/08/cake-contribution-organization

We are currently going through a process of increasing the visibility of addins, and also trying to ensure their long term maintainability.

To that end, we are asking addin creators to add the cake-contrib user on NuGet as a co-owner (this can be done through the NuGet website by clicking on Manage Owners on the package page).

Would you be interested in doing this? If you have any questions about this, please let me know. There was some initial concern that the Cake Team were trying to "take over" packages, and that couldn't be further from the truth, and if you have this concern, or others, I would like to address them.

Thanks!

**Comment by hadi77ir** [comment]
@gep13 Done. :)

**Comment by gep13** [comment]
@hadi77ir thank you for taking the time to do this!  Can you confirm what process you have followed to do this, as I haven't had any emails to accept the request to join, thanks!

**Comment by gep13** [comment]
@hadi77ir ignore me, I found the request to accept the package which I have now done.  Thank you!

As a follow up question, would you be interested in moving this repository under the Cake Contrib Organisation on GitHub?

This would allow other people, myself included, to help with the maintenance of the addin.

What do you think?  You would still have full permissions to the repository in the same way as you do now, it is just that it would live under an Organisation.

More information about this request, and why I am sending you this, are again detailed in the blog post:

https://cakebuild.net/blog/2016/08/cake-contribution-organization

**Comment by hadi77ir** [comment]
@gep13 I agree to do so.

**Comment by gep13** [comment]
@hadi77ir that is great news! Due to the way GitHub works you would need to transfer the repository initially to my account gep13, and from there I will move it to the Organisation, and get you set up with permissions. Does that sound on?

**Comment by hadi77ir** [comment]
@gep13 Repo transfer request has been sent.

**Comment by gep13** [comment]
@hadi77ir that is great, thank you!  I have just transferred the repository into the Organisation, however, when trying to invite you into the Organisation, I am getting this error:

![image](https://user-images.githubusercontent.com/1271146/61997492-1a0ca800-b09a-11e9-928a-0fdb7cf561fd.png)

So looks like there is an error with GitHub.  I will continue to try, and I will let you know as soon as I have been able to give you permissions.

Do you also have a Twitter account and use Slack?  These are two mechanisms that we use to keep in contact with Cake Addin Maintainers.  If you let me know your details, I can get you added.  Thanks

**Comment by hadi77ir** [comment]
@gep13 That might be due to restrictions imposed by GitHub on Iranians during the last week.

Yes I have a [Twitter account](https://twitter.com/hadi77ir). Also, I can't use Slack because of U.S. sanctions on Iranians. :disappointed_relieved:

**Comment by gep13** [comment]
Oh, I wasn’t aware of any restrictions that were put in place. I will follow up directly with GitHub support to see what is going on.

The Slack Team is used to allow Cake Addin Maintainers to discuss things. We also have a Gitter Room that you might be able to use. On phone just now, but I will post the link to the room here when back on computer.

**Comment by gep13** [comment]
@hadi77ir the Gitter Room is here: https://gitter.im/cake-contrib/Lobby

**Comment by gep13** [comment]
@hadi77ir just to keep you posted on this...

I have raised a support ticket, and I am working with the GitHub Team to figure out what is going on.  I have been told that since this is a public repository, and all the work on it is OSS, that you should be able to have access.

I will keep you posted as I hear back from support on this.

**Comment by hadi77ir** [comment]
@gep13 Thanks. That's some good news.

**Comment by gep13** [comment]
@hadi77ir I have just been able to send you a request to join the Cake-Contrib Organisation.  Can you please confirm if you have received it, and whether you have been able to join?  Thanks

**Comment by hadi77ir** [comment]
@gep13 Yes, I accepted the request, and now I'm a part of the organization.

**Comment by gep13** [comment]
@hadi77ir that is great news!  I am so glad that we were able to get this sorted out.  I felt so bad that I wasn't able to give you permissions to your own repository.

Please feel free to reach out if you have any questions!

**Comment by hadi77ir** [comment]
@gep13 Thanks so much! :)
